myproject/myapp/urls.py
from django.urls import path ,include,translate_url
from . import views 
app_name = "myapp"
urlpatterns= [
     path("index", views.index, name="index"),
     #path("404", views.404 , name="404"),
     path("contact", views.contact, name="contact"),
     
     path("About", views.About, name="About"),
   
    path('blog', views.post_list.as_view(), name='post_list'),
    path('<slug:slug>/', views.post_detail.as_view(), name='post_detail'),

     ]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
           
]

myproject/myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class contact1(models.Model):
    
    first_name=models.CharField(max_length=300)
    last_name=models.CharField(max_length=350)
    email=models.EmailField(default=None)
    Username=models.CharField(max_length=150,default=True)
   # password=models.DO_NOTHING
    subject=models.TextField()
    message=models.TextField()

    def __str__(self):
        return self.Username
STATUS = ((0,"draft"),
          (1, "publish"))
class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title








myproject/myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import contact1
from django.forms import ModelForm


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user
from django.forms import ModelForm



class ContactForm(ModelForm):
    class Meta:
        model = contact1
        fields = '__all__'

myproject/myapp/views.py
from django.shortcuts import render,redirect
from .models import contact1,Post
from .forms import ContactForm
from django.views import generic
# Create your views here.



def About(request):
 return render(request, 'About.html')
     
def index(request):
  return render(request, 'index.html')
def contact(request):
                 
         if request.method=="POST":
          #cont=contact.objects.all()
           form=ContactForm(request.POST)
           if form.is_valid():
               form.save()
               return redirect("sucess")
         form = ContactForm()
         context = {'form': form}
         
         return render(request, 'contact.html')



class post_list(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'post_list.html'

class post_detail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'







    


      
    



myproject/templates/About.html


  
 <center><body>
  
  <div class="bg-light">
    <div class="container py-5">
      <div class="row h-100 align-items-center py-5">
        <div class="col-lg-6">
          <h1 class="display-4" >About us</h1>
          <br>
          <h1><p class="lead text-muted mb-0" style="border: 100px; color:aqua"    >Introduction</p></h1>
         <h2 style="color: cornflowerblue;"> <p>When we started Dugsiiye Online Courses back
             in 2018, our goal was to give Somalis from all across the world 
            the ability to learn the skills they’d need to succeed in this modern century. We
             set out to create a new, interactive way of learning — making it engaging, flexible, 
             and accessible for 
             as many people as possible. Since then, we have helped hundreds of Somali people worldwide unlock modern
              technical skills and reach their full potential through code. There are two commitments we've made to the
               world. We've been grounded by these since day one: Increase access to high-quality education for everyone, 
               everywhere; Enhance teaching and learning online through research.</p></h2>

               <h1>Our vision </h1>
               <h2>
                To reach out to all Somali communities through
                 knowledge and to be a comprehensive online institute 
                 that offers quality-oriented
                 education and accredited certification.</h2>


                 <h1 style="color:cadetblue ;">Our Mission </h1>
                 <h2 style="color:aqua">We want to create a world where anyone can build something meaningful with technology, and everyone has the
                  learning tools, resources, and opportunities to do so. Code contains a world of possibilities — all that’s required 
                  is the curiosity and drive to learn. At Dugsiiye, we are dedicated to empowering all people, regardless of where they are in their 
                 coding journeys, to continue to learn, grow, and make an impact on the world around them.></h2>
        
        </div>
        <div class="col-lg-6 d-none d-lg-block"><img src="https://bootstrapious.com/i/snippets/sn-about/illus.png" alt="" class="img-fluid"></div>
      </div>
    </div>

  </div>
  
  <div class="bg-white py-5">
    <div class="container py-5">
      <div class="row align-items-center mb-5">
        <div class="col-lg-6 order-2 order-lg-1"><i class="fa fa-bar-chart fa-2x mb-3 text-primary"></i>
          <h2 class="font-weight-light">Lorem ipsum dolor sit amet</h2>
          <p class="font-italic text-muted mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><a href="#" class="btn btn-light px-5 rounded-pill shadow-sm">Learn More</a>
        </div>
        <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src="https://bootstrapious.com/i/snippets/sn-about/img-1.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
      </div>
      <div class="row align-items-center">
        <div class="col-lg-5 px-5 mx-auto"><img src="https://bootstrapious.com/i/snippets/sn-about/img-2.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
        <div class="col-lg-6"><i class="fa fa-leaf fa-2x mb-3 text-primary"></i>
         
        </div>
      </div>
    </div>
  </div>
  
  <div class="bg-light py-5">
    <div class="container py-5">
      <div class="row mb-4">
        <div class="col-lg-5">
          <h2 class="display-4 font-weight-light">Our team</h2>
          <p class="font-italic text-muted">Here we dedicated, experienced and skilled Team .</p>
        </div>
      </div>
  
      <div class="row text-center">
        <!-- Team item-->
        <div class="col-xl-3 col-sm-6 mb-5">
          <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://bootstrapious.com/i/snippets/sn-about/avatar-4.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
            <h5 class="mb-0">Sacdiyo Abdi </h5><span class="small text-uppercase text-muted">Secretary</span>
            <ul class="social mb-0 list-inline mt-3">
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
        <!-- End-->
  
        <!-- Team item-->
        <div class="col-xl-3 col-sm-6 mb-5">
          <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://bootstrapious.com/i/snippets/sn-about/avatar-3.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
            <h5 class="mb-0">Abubakar Warsame </h5><span class="small text-uppercase text-muted">CEO - Founder</span>
            <ul class="social mb-0 list-inline mt-3">
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
        <!-- End-->
  
        <!-- Team item-->
        <div class="col-xl-3 col-sm-6 mb-5">
          <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://bootstrapious.com/i/snippets/sn-about/avatar-2.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
            <h5 class="mb-0">Khadar Adan </h5><span class="small text-uppercase text-muted">Member</span>
            <ul class="social mb-0 list-inline mt-3">
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
        <!-- End-->
  
        <!-- Team item-->
        <div class="col-xl-3 col-sm-6 mb-5">
            <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://bootstrapious.com/i/snippets/sn-about/avatar-1.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
            <h5 class="mb-0">Abdikarin Husen </h5><span class="small text-uppercase text-muted">Member </span>
            <ul class="social mb-0 list-inline mt-3">
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
        <!-- End-->
  
      </div>
    </div>
  </div>
  
</body>
</center>
  <footer class="bg-light pb-5">
    <div class="container text-center">
      <p class="font-italic text-muted mb-0">&copy; Copyrights YaqiinOnline.com All rights reserved.</p>
    </div>
  </footer>

myproject/templates/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>Django Central</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'myapp:post_list' %}"> YaqiinOnline</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="About">About</a>
                 
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Copyright &copy; YaqiinOnline</p>
        </footer>
    </body>

{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
        <a href="http://127.0.0.1:8000/index"
           class="btn btn-danger">Know more!</a>
    </div>
</div>
</div>

{% endblock sidebar %}
</html>

myproject/templates/contact.html
<!--Section: Contact v.2-->
<section class="mb-4">

  <!--Section heading-->
  <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
  <body style="padding: 20px;
  resize: both;
  width: 1000%;
  height: 100%;
  margin: 50px auto;
  position: relative;">
  <!--Section description-->
  <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
      a matter of hours to help you.</p>

  <div class="row">

      <!--Grid column-->
      <div class="col-md-9 mb-md-0 mb-5">
          <form id="contact-form" name="contact-form" action="mail.php" method="POST"    style="  width: 1000px;
          height: 100px;">

              <!--Grid row-->
              <div class="row">

                  <!--Grid column-->
                  <div class="col-md-6">
                      <div class="md-form mb-0" style=" width: 500px;">
                          <input type="text" id="name" name="name" class="form-control">
                          <label for="name" class="">Your name</label>
                      </div>
                  </div>
                  <!--Grid column-->

                  <!--Grid column-->
                  <div class="col-md-6">
                      <div class="md-form mb-0">
                          <input type="text" id="email" name="email" class="form-control">
                          <label for="email" class="">Your email</label>
                      </div>
                  </div>
                  <!--Grid column-->

              </div>
              <!--Grid row-->

              <!--Grid row-->
              <div class="row">
                  <div class="col-md-12">
                      <div class="md-form mb-0">
                          <input type="text" id="subject" name="subject" class="form-control">
                          <label for="subject" class="">Subject</label>
                      </div>
                  </div>
              </div>
              <!--Grid row-->

              <!--Grid row-->
              <div class="row">

                  <!--Grid column-->
                  <div class="col-md-12">

                      <div class="md-form">
                          <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                          <label for="message">Your message</label>
                      </div>

                  </div>
              </div>
              <!--Grid row-->

          </form>

          <div class="text-center text-md-left">
              <a class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
          </div>
          <div class="status"></div>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-3 text-center">
          <ul class="list-unstyled mb-0">
              <li><i class="fas fa-map-marker-alt fa-2x"></i>
                  <p>San Francisco, CA 94126, USA</p>
              </li>

              <li><i class="fas fa-phone mt-4 fa-2x"></i>
                  <p>+ 01 234 567 89</p>
              </li>

              <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                  <p>contact@mdbootstrap.com</p>
              </li>
          </ul>
      </div>
      <!--Grid column-->

  </div>

</section>
<!--Section: Contact v.2-->
</body>

myproject/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css' %}" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Latest bootstrib CSS -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{% static 'responsive.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>YaqiinOnline.com</title>
    <link rel="stylesheet" href="https://developer.mozilla.org/docs/Web/CSS/color">
</head>
<body>
    <header>
       <div class="containe-head">
         <div class="logo">
             <img src="{% static 'img/abu4.png' %}" alt="" srcset="">
         </div>
           <div class="navbar">
                <ul>
                   <li onclick="homePage()">Home</li>
                    <li onclick="postPage()">Courses</li>
                   
                    <a href="blog"> <li onclick="logIn(contact.html)">blog</li></a>
                    <a href="About"> <li onclick="logIn(contact.html)">About</li></a> 
                  <a href="contact"> <li onclick="logIn(contact.html)">Contact</li></a> 
                </ul>
           </div>
       </div>
    </header>

    <!-- main containe -->
<div id="home">
    <section id="main">
        <div class="bannar">
            <img src="{% static 'img/abu3.jpg' %}" alt="" srcset="">
           <!-- <h1 class="site-titel" style="color: hotpink;">Yaqiin.com</h1> -->
            <div class="search-div">
                 
                <center> <p> <h1 style="color: aqua;" class="title"></h1></center>
               <h2 style="color:chartreuse;"  class="anim">  <marquee behavior="" direction=""> we aspire to create outstanding academy that promote educational excellence, character development and service to communities </marquee></h2></p>
            </div>
        </div>
        <div class="news-update">
            
            <marquee behavior="" direction="">
        <h1 style="color:1FAB89">We’re committed to changing the future of learning for the better and provide the tools and skills to teach what you love.</h1>
         </marquee>
        </div>
    
            <h1>most popular courses we Give </h1>
            <hr id="card-hr"/>
        <div class="card">
                <div class="card-element">
                    <div class="img">
                        <img src="{% static 'img/abu2.png' %}" alt="" srcset="">
                    </div>
                    <h3 ><i class="fa-solid fa-house-chimney-user"></i><span id="card-titel">Python master class from basic to advance</span></h3>
                    <p id="institute-dris"><i class="fa-solid fa-location-dot"></i>IT takes only 35 days </p>
                    <div class="card-butt">
                        <button class="card-sub-butt" id="butt-follow"><i class="fa-solid fa-star"></i></button>
                        <div class="g-start-2" style="grid-row: 2">Programming</div>
                    </div>
                </div>
            <!-- 2 -->
            <div class="card-element">
                <div class="img">
                    <img src="{% static './img/abu2.png' %}" alt="" srcset="">
                </div>
                <h3 ><i class="fa-solid fa-house-chimney-user"></i><span id="card-titel">Python master class from basic to advance</span></h3>
                <p id="institute-dris"><i class="fa-solid fa-location-dot"></i>IT takes only 35 days </p>
                <div class="card-butt">
                    <button class="card-sub-butt" id="butt-follow"><i class="fa-solid fa-star"></i></button>
                    <div class="g-start-2" style="grid-row: 2">Programming</div>
                </div>
            </div>
            <!-- 3-->
            <div class="card-element">
                <div class="img">
                    <img src="{% static './img/abu2.png' %}" alt="" srcset="">
                </div>
                <h3 ><i class="fa-solid fa-house-chimney-user"></i><span id="card-titel">Python master class from basic to advance</span></h3>
                <p id="institute-dris"><i class="fa-solid fa-location-dot"></i>IT takes only 35 days </p>
                <div class="card-butt">
                    <button class="card-sub-butt" id="butt-follow"><i class="fa-solid fa-star"></i></button>
                    <div class="g-start-2" style="grid-row: 2">Programming</div>
                </div>
            </div>
            <!-- 4-->
            <div class="card-element">
                <div class="img">
                    <img src="{% static './img/abu2.png' %}" alt="" srcset="">
                </div>
                <h3 ><i class="fa-solid fa-house-chimney-user"></i><span id="card-titel">Python master class from basic to advance</span></h3>
                <p id="institute-dris"><i class="fa-solid fa-location-dot"></i>IT takes only 35 days </p>
                <div class="card-butt">
                    <button class="card-sub-butt" id="butt-follow"><i class="fa-solid fa-star"></i></button>
                    <div class="g-start-2" style="grid-row: 2">Programming</div>
                </div>
            </div>
                
    </div>

    <div class="page-number">
        <div class="pagination">
            <a href="#">&laquo;</a>
            <a href="#">1</a>
            <a class="active" href="About">2</a>
            <a href="blog">3</a>
            <a href="#">4</a>
           
          </div>
    </div>

</section>

<!-- log in -->
<section id="login">
    
<div id="login-container">
    <div class="regation">
        <form action="">
            <h3>Log in</h3>
            <div class="inputBox">
                <span>User-Name</span>
                <div class="box">
                    <div class="icon"><ion-icon name="person"></ion-icon></div>
                    <input type="text" name="" id="">
                </div>
            </div>
            <div class="inputBox">
                <span>Password</span>
                <div class="box">
                    <div class="icon"><ion-icon name="lock-closed"></ion-icon></div>
                    <input type="password" name="" id="">
                </div>
            </div>
            <label for="">
                <input type="checkbox" name="" id="" value="Log In">Remember me
            </label>
            <div class="inputBox">
                <div class="box">
                    <input type="submit" name="" id="">
                </div>
            </div>
            <a href="#" class="forgot"> Forget Password</a>
            <a href="#" class="forgot"> Regation</a>
        </form>        

    </div>
</div>
</section>


<!-- footer section -->
    <footer id="footer">
        <div class="footer-main-section f">
            <div class="footer-section-1">
                <div class="footer-logo">
                    <img src="{% static './img/abu4.png' %}" alt="" srcset="">
                </div>
              
            </div>
          
          
            <div class="footer-section-4">
                <div class="footer-social-icone" >
                    <li>
                    <h4><a href="#"><i class="footer-icon fa-regular fa-envelope"></i>Email</h4> </a><br/>
                    <h4><a href="#"> <i class=" footer-icon fa-regular fa-envelope"></i>Facebook</h4></a><br/>
                    <h4><a href="#"> <i class=" footer-icon fa-regular fa-envelope"></i>YouTub</h4></a><br/>
                    <h4><a href="#"> <i class=" footer-icon fa-regular fa-envelope"></i>twitter</h4></a>
                </li>
                </div>
            </div>
        </div>
    </footer>

    <div class="brand">
        <small>2023 &copy; YaqiinOnline.com</small>
    </div>

    <script type="text/javascript" src="{% static 'js.js' %}"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script> -->

    <script type="module" src="{% static 'https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js' %}"></script>
    <script nomodule src="{% static 'https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js' %}"></script>
</body>
</html>

myproject/templates/post_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
  </div>
</div>

{% endblock content %}

myproject/templates/post_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                    <p class="text-light">We Love Django As much as you do..! &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
      
    </div>
</div>
{%endblock%}

myproject/templates/sucess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>sucess</title>
</head>
<body>
    <h1> You have sucessfully submitted</h1>
</body>
</html>